### ISSUE TITLE
Restart monasca-thresh cause connection refused

### ISSUE THREAD

**Issue by M425** [hpcloud-mon/ansible-monasca-thresh#20]
I'm executing this role from the [monasca-installer](https://github.com/hpcloud-mon/monasca-installer) using vagrant and a single monasca node.
I had to minor fix something among the roles to make them work (just minor things), but I changed nothing on this role (except the download, it doesn't download the monasca-thresh.jar from internet but it directly copy from the `./files/` folder, just to speed up the script cause i got different errors).

I get the following error.

```
NOTIFIED: [monasca-thresh | restart monasca-thresh] *************************** 

<192.168.10.6> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.10.6> REMOTE_MODULE service name=monasca-thresh state=restarted enabled=yes
<192.168.10.6> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/mat/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentic
ation=no -o User=vagrant -o ConnectTimeout=10 192.168.10.6 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1443716361.45-32011369579007 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1443716361.45-32011369579007 && echo $HOME/.ansible/tmp/ansible-tmp-1443716361.45-32011
369579007'
<192.168.10.6> PUT /tmp/tmpgAQdzF TO /home/vagrant/.ansible/tmp/ansible-tmp-1443716361.45-32011369579007/service
<192.168.10.6> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/mat/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentic
ation=no -o User=vagrant -o ConnectTimeout=10 192.168.10.6 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=iafzohbqnyviiebrqmvhumcsagotlemf] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-iafzohbqnyviiebrqmvhumcsagotlemf; LANG=en_US.UTF-8 LC_CTYPE=en
_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1443716361.45-32011369579007/service; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1443716361.45-32011369579007/ >/dev/null 2>&1'"'"''

failed: [192.168.10.6] => {"failed": true}
msg: Exception in thread "main" org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)
        at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
        at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75)
        at backtype.storm.command.kill_topology$_main.doInvoke(kill_topology.clj:26)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at backtype.storm.command.kill_topology.main(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)
        ... 5 more
Exception in thread "main" org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)
        at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
        at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75)
        at backtype.storm.command.list$_main.invoke(list.clj:22)
        at clojure.lang.AFn.applyToHelper(AFn.java:159)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at backtype.storm.command.list.main(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)
        ... 6 more
Exception in thread "main" org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)
        at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
        at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75)
        at backtype.storm.command.list$_main.invoke(list.clj:22)
        at clojure.lang.AFn.applyToHelper(AFn.java:159)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at backtype.storm.command.list.main(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)
        ... 6 more
Exception in thread "main" java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused
        at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:38)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:116)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:70)
        at monasca.thresh.ThresholdingEngine.run(ThresholdingEngine.java:114)
        at monasca.thresh.ThresholdingEngine.main(ThresholdingEngine.java:88)
Caused by: org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)
        at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
        at backtype.storm.security.auth.SimpleTransportPlugin.connect(SimpleTransportPlugin.java:83)
        at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:63)
        at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:47)
        at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:43)
        at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:36)
        ... 4 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)
        ... 10 more


FATAL: all hosts have already failed -- aborting

TASK: [monasca-thresh | Enable and Start Monasca-thresh] ********************** 
FATAL: no hosts matched or all hosts have already failed -- aborting
```

**Comment by ddieterly** [comment]
## Is storm running?

Deklan Dieterly
Senior Systems Software Engineer
HPE

**Comment by M425** [comment]
No other ansible errors came up before (storm role is processed earlier), but actually the upstart service (the vagrant os is an ubuntu) is not recognized by `service storm status`, furthermore i check up the directory and files and seems ok, the log files in `/var/log/storm/` are all empty but `supervisor.log` which is:

```
2015-10-01 15:51:11 o.a.s.c.r.ExponentialBackoffRetry [WARN] maxRetries too large (60). Pinning to 29
2015-10-01 15:51:12 o.a.s.c.CuratorZookeeperClient [WARN] session timeout [3000] is less than connection timeout [15000]
2015-10-01 15:51:13 o.a.s.c.r.ExponentialBackoffRetry [WARN] maxRetries too large (60). Pinning to 29
2015-10-01 15:51:13 o.a.s.c.CuratorZookeeperClient [WARN] session timeout [3000] is less than connection timeout [15000]
```

`ps aux | grep storm` print this

```
storm    25747  1.9  8.3 2407612 170592 ?      Ssl  19:04   1:21 java -server -Dstorm.options= -Dstorm.home=/opt/storm/apache-storm-0.9.5 -Dstorm.log.dir=/opt/storm/apache-storm-0.9.5/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /opt/storm/apache-storm-0.9.5/lib/ring-core-1.1.5.jar:/opt/storm/apache-storm-0.9.5/lib/jetty-util-6.1.26.jar:/opt/storm/apache-storm-0.9.5/lib/objenesis-1.2.jar:/opt/storm/apache-storm-0.9.5/lib/jgrapht-core-0.9.0.jar:/opt/storm/apache-storm-0.9.5/lib/commons-lang-2.5.jar:/opt/storm/apache-storm-0.9.5/lib/storm-core-0.9.5.jar:/opt/storm/apache-storm-0.9.5/lib/math.numeric-tower-0.0.1.jar:/opt/storm/apache-storm-0.9.5/lib/commons-exec-1.1.jar:/opt/storm/apache-storm-0.9.5/lib/commons-io-2.4.jar:/opt/storm/apache-storm-0.9.5/lib/compojure-1.1.3.jar:/opt/storm/apache-storm-0.9.5/lib/carbonite-1.4.0.jar:/opt/storm/apache-storm-0.9.5/lib/core.incubator-0.1.0.jar:/opt/storm/apache-storm-0.9.5/lib/clojure-1.5.1.jar:/opt/storm/apache-storm-0.9.5/lib/commons-logging-1.1.3.jar:/opt/storm/apache-storm-0.9.5/lib/clout-1.0.1.jar:/opt/storm/apache-storm-0.9.5/lib/hiccup-0.3.6.jar:/opt/storm/apache-storm-0.9.5/lib/asm-4.0.jar:/opt/storm/apache-storm-0.9.5/lib/commons-fileupload-1.2.1.jar:/opt/storm/apache-storm-0.9.5/lib/joda-time-2.0.jar:/opt/storm/apache-storm-0.9.5/lib/ring-jetty-adapter-0.3.11.jar:/opt/storm/apache-storm-0.9.5/lib/logback-classic-1.0.13.jar:/opt/storm/apache-storm-0.9.5/lib/tools.logging-0.2.3.jar:/opt/storm/apache-storm-0.9.5/lib/chill-java-0.3.5.jar:/opt/storm/apache-storm-0.9.5/lib/kryo-2.21.jar:/opt/storm/apache-storm-0.9.5/lib/snakeyaml-1.11.jar:/opt/storm/apache-storm-0.9.5/lib/log4j-over-slf4j-1.6.6.jar:/opt/storm/apache-storm-0.9.5/lib/clj-stacktrace-0.2.2.jar:/opt/storm/apache-storm-0.9.5/lib/jline-2.11.jar:/opt/storm/apache-storm-0.9.5/lib/minlog-1.2.jar:/opt/storm/apache-storm-0.9.5/lib/json-simple-1.1.jar:/opt/storm/apache-storm-0.9.5/lib/logback-core-1.0.13.jar:/opt/storm/apache-storm-0.9.5/lib/disruptor-2.10.1.jar:/opt/storm/apache-storm-0.9.5/lib/commons-codec-1.6.jar:/opt/storm/apache-storm-0.9.5/lib/ring-devel-0.3.11.jar:/opt/storm/apache-storm-0.9.5/lib/tools.macro-0.1.0.jar:/opt/storm/apache-storm-0.9.5/lib/tools.cli-0.2.4.jar:/opt/storm/apache-storm-0.9.5/lib/clj-time-0.4.1.jar:/opt/storm/apache-storm-0.9.5/lib/reflectasm-1.07-shaded.jar:/opt/storm/apache-storm-0.9.5/lib/jetty-6.1.26.jar:/opt/storm/apache-storm-0.9.5/lib/ring-servlet-0.3.11.jar:/opt/storm/apache-storm-0.9.5/lib/slf4j-api-1.7.5.jar:/opt/storm/apache-storm-0.9.5/lib/servlet-api-2.5.jar:/opt/storm/apache-storm-0.9.5/conf -Xmx1024m -Dlogfile.name=supervisor.log -Dlogback.configurationFile=/opt/storm/apache-storm-0.9.5/logback/cluster.xml backtype.storm.daemon.supervisor
```

**Comment by M425** [comment]
Solved:
thanks for the storm hint :+1:, actually the issue was there. The problem comes from my choice of the all-in-one monasca version (actually it lacks of docs in monasca-installer repo) instead of 3 node monasca. 
So I changed the `vagrant_config.yml` file from 

```
master_config:
  # Enable/disable services
  storm_nimbus_enabled: false
  storm_supervisor_enabled: true
```

to

```
master_config:
  # Enable/disable services
  storm_nimbus_enabled: true
  storm_supervisor_enabled: true
```

and in this way the complete storm was running on my vm. After that i double checked the correctness by launching `service storm-nimbus status` and `service storm-supervisor status`, both running. the `monasca-installer` ansible playbook passes that task :smile: (stopped again later though :weary: ... but this is another issue)
